on: [push]

jobs:
  sobelow_job:
    runs-on: ubuntu-latest
    name: Sobelow Job
    steps:
      - uses: actions/checkout@v2
      - id: run-action
        uses: karangejo/sobelow-umbrella-action@v1.10
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif